platform:
  type: "napcat" # 消息平台，兼容napcat, llonebot, lagrange
  http_host: "127.0.0.1" # 非docker部署一般为127.0.0.1，docker部署一般为宿主机局域网ip
  http_port: 2333 # 消息平台监听端口，通常为3000或2333
  api_token: "" # http服务器token，没有则不填

request:
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
  website: "e-hentai"  # 表站: e-hentai | 里站: exhentai
  cookies: # 缺少有效cookie时请不要将website设置为exhentai
    ipb_member_id: ""
    ipb_pass_hash: ""
    igneous: ""
  proxies: "" # 墙内用户必填项，代理软件位于宿主机时，非docker部署一般为http://127.0.0.1:port，docker部署一般为http://{宿主机局域网ip}:port
  concurrency: 5 # 并发数量限制，在我的机器上超过5偶尔会有图片丢失问题
  max_retries: 10 # 请求重试次数
  timeout: 30 # 超时时间

output:
  image_folder: "/app/sharedFolder/tempImages" # 暂时存放画廊图片的文件夹路径
  pdf_folder: "/app/sharedFolder/ehentai" # 存放pdf文件的路径
  jpeg_quality: 85 # 图片质量，100为不压缩，85左右可以达到文件大小和质量的最佳平衡
  max_pages_per_pdf: 200 # 单个pdf文件最大页数

# 注意：
# 如果你是docker部署，请务必为消息平台容器挂载pdf文件所在的文件夹，否则消息平台将无法解析文件路径
#
# 我是这样做的：
#   对langbot: /vol3/1000/dockerSharedFolder -> /app/sharedFolder
#   对napcat: /vol3/1000/dockerSharedFolder -> /app/sharedFolder
