platform:
  type: "napcat" # 消息平台，兼容napcat, llonebot, lagrange
  http_host: "127.0.0.1" # http服务器ip，非docker部署一般为127.0.0.1，docker部署一般为宿主机局域网ip
  http_port: 2333 # http服务器端口，通常为2333或3000
  api_token: "" # http服务器token，没有则不填

request:
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
  website: "e-hentai"  # 表站: e-hentai | 里站: exhentai
  cookies: # 缺少有效cookie时请不要将website设置为exhentai
    ipb_member_id: ""
    ipb_pass_hash: ""
    igneous: ""
  proxies: "" # 代理设置（墙内用户必填项），代理软件位于宿主机时，非docker部署一般为http://127.0.0.1:port，docker部署一般为http://{宿主机局域网ip}:port
  concurrency: 10 # 并发数量限制
  max_retries: 3 # 请求重试次数，如果你的代理不稳定或带宽不够建议适量增加次数
  timeout: 5 # 超时时间，同上

output:
  image_folder: "/app/sharedFolder/ehentai/tempImages" # 缓存画廊图片的路径
  pdf_folder: "/app/sharedFolder/ehentai/pdf" # 存放pdf文件的路径
  search_cache_folder: "/app/sharedFolder/ehentai/searchCache" # 缓存每个用户搜索结果的路径
  jpeg_quality: 85 # 图片质量，100为不压缩，85左右可以达到文件大小和图片质量的最佳平衡
  max_pages_per_pdf: 200 # 单个pdf文件最大页数

# 注意：
# 如果你是docker部署，请务必为消息平台容器挂载pdf文件所在的文件夹，否则消息平台将无法解析文件路径
#
# 我是这样做的：
#   对langbot: /vol3/1000/dockerSharedFolder -> /app/sharedFolder
#   对napcat: /vol3/1000/dockerSharedFolder -> /app/sharedFolder
